"""Hand-written Phase 2A fixtures, not generated by production placement code.

Rows are classical mnemonic expansions in canonical branch/hour order; source
and transcription decisions are recorded in README's Phase 2A source audit.
"""

NAMES = ("左輔", "右弼", "文昌", "文曲", "天魁", "天鉞", "祿存",
         "擎羊", "陀羅", "天馬", "火星", "鈴星", "地空", "地劫")
BRANCHES = tuple("子丑寅卯辰巳午未申酉戌亥")
MONTH_ROWS = tuple(zip("辰巳午未申酉戌亥子丑寅卯", "戌酉申未午巳辰卯寅丑子亥"))
CHANG_QU_ROWS = tuple(zip("戌酉申未午巳辰卯寅丑子亥", "辰巳午未申酉戌亥子丑寅卯"))
KONG_JIE_ROWS = tuple(zip("亥戌酉申未午巳辰卯寅丑子", "亥子丑寅卯辰巳午未申酉戌"))
STEM_ROWS = (
    ("甲", "丑", "未", "寅", "卯", "丑"),
    ("乙", "子", "申", "卯", "辰", "寅"),
    ("丙", "亥", "酉", "巳", "午", "辰"),
    ("丁", "亥", "酉", "午", "未", "巳"),
    ("戊", "丑", "未", "巳", "午", "辰"),
    ("己", "子", "申", "午", "未", "巳"),
    ("庚", "丑", "未", "申", "酉", "未"),
    ("辛", "午", "寅", "酉", "戌", "申"),
    ("壬", "卯", "巳", "亥", "子", "戌"),
    ("癸", "卯", "巳", "子", "丑", "亥"),
)
HORSE_ROWS = tuple(zip(BRANCHES, "寅亥申巳寅亥申巳寅亥申巳"))
# Explicit complete hour rows per trine, indexed by 子..亥, no modulo formulas.
FIRE_BELL_ROWS = (
    ("寅午戌", "丑寅卯辰巳午未申酉戌亥子", "卯辰巳午未申酉戌亥子丑寅"),
    ("申子辰", "寅卯辰巳午未申酉戌亥子丑", "戌亥子丑寅卯辰巳午未申酉"),
    ("巳酉丑", "卯辰巳午未申酉戌亥子丑寅", "戌亥子丑寅卯辰巳午未申酉"),
    ("亥卯未", "酉戌亥子丑寅卯辰巳午未申", "戌亥子丑寅卯辰巳午未申酉"),
)
FULL_CASES = (
    ("A", "2025-01-29", 0, 30, "辰戌戌辰子申卯辰寅亥卯戌亥亥"),
    ("B", "2025-01-29", 1, 30, "辰戌酉巳子申卯辰寅亥辰亥戌子"),
    ("C", "2024-02-29", 12, 0, "辰戌辰戌丑未寅卯丑寅申辰巳巳"),
    ("L", "2025-07-25", 12, 0, "戌辰辰戌子申卯辰寅亥酉辰巳巳"),
)
# Phase 2A-R: month 7 gives 左輔戌 / 右弼辰; retain all prior 12 positions.
LEAP_FULL = dict(zip(NAMES, "戌辰辰戌子申卯辰寅亥酉辰巳巳"))
LEAP_YEAR_HOUR = dict(zip(NAMES[2:], "辰戌子申卯辰寅亥酉辰巳巳"))
LATE_ZI = dict(zip(NAMES, "酉巳戌辰子申卯辰寅亥卯戌亥亥"))
