"""Hand-reviewed complete core charts, not generated by Tiger-ZiWei.

Provenance: Phase 1B CWA/HKO lunar/Ganzhi references; Quan Shu vol.2
安身命例 / 安十二宮例 / 起五行寅例 / 納音 / birthday charts / star sequence.
All twelve rows per chart are explicit, branch-ordered literals. Star lists
include every major star once; no production helper generates expectations.
Reviewed 2026-10-05. Row = branch, palace name, Ganzhi, Body marker, major stars.
"""

STATIC_CHARTS = [
    {
        "solar": "2025-01-29", "hour": 0, "minute": 30, "gender": "female",
        "lunar": (2025, 1, 1, False), "ganzhi": ("乙巳", "丁丑", "戊戌", "壬子"),
        "life": "寅", "body": "寅", "body_name": "命宮", "life_ganzhi": "戊寅",
        "bureau": ("土五局", 5),
        "palaces": [
            ("子", "夫妻宮", "戊子", False, ("貪狼",)),
            ("丑", "兄弟宮", "己丑", False, ("天同", "巨門")),
            ("寅", "命宮", "戊寅", True, ("武曲", "天相")),
            ("卯", "父母宮", "己卯", False, ("太陽", "天梁")),
            ("辰", "福德宮", "庚辰", False, ("七殺",)),
            ("巳", "田宅宮", "辛巳", False, ("天機",)),
            ("午", "官祿宮", "壬午", False, ("紫微",)),
            ("未", "交友宮", "癸未", False, ()),
            ("申", "遷移宮", "甲申", False, ("破軍",)),
            ("酉", "疾厄宮", "乙酉", False, ()),
            ("戌", "財帛宮", "丙戌", False, ("廉貞", "天府")),
            ("亥", "子女宮", "丁亥", False, ("太陰",)),
        ],
    },
    {
        "solar": "2025-01-29", "hour": 1, "minute": 30, "gender": "female",
        "lunar": (2025, 1, 1, False), "ganzhi": ("乙巳", "丁丑", "戊戌", "癸丑"),
        "life": "丑", "body": "卯", "body_name": "福德宮", "life_ganzhi": "己丑",
        "bureau": ("火六局", 6),
        "palaces": [
            ("子", "兄弟宮", "戊子", False, ("天梁",)),
            ("丑", "命宮", "己丑", False, ("廉貞", "七殺")),
            ("寅", "父母宮", "戊寅", False, ()),
            ("卯", "福德宮", "己卯", True, ()),
            ("辰", "田宅宮", "庚辰", False, ("天同",)),
            ("巳", "官祿宮", "辛巳", False, ("武曲", "破軍")),
            ("午", "交友宮", "壬午", False, ("太陽",)),
            ("未", "遷移宮", "癸未", False, ("天府",)),
            ("申", "疾厄宮", "甲申", False, ("天機", "太陰")),
            ("酉", "財帛宮", "乙酉", False, ("紫微", "貪狼")),
            ("戌", "子女宮", "丙戌", False, ("巨門",)),
            ("亥", "夫妻宮", "丁亥", False, ("天相",)),
        ],
    },
    {
        "solar": "2024-02-29", "hour": 12, "minute": 0, "gender": "female",
        "lunar": (2024, 1, 20, False), "ganzhi": ("甲辰", "丙寅", "癸亥", "戊午"),
        "life": "申", "body": "申", "body_name": "命宮", "life_ganzhi": "壬申",
        "bureau": ("金四局", 4),
        "palaces": [
            ("子", "官祿宮", "丙子", False, ("貪狼",)),
            ("丑", "交友宮", "丁丑", False, ("天同", "巨門")),
            ("寅", "遷移宮", "丙寅", False, ("武曲", "天相")),
            ("卯", "疾厄宮", "丁卯", False, ("太陽", "天梁")),
            ("辰", "財帛宮", "戊辰", False, ("七殺",)),
            ("巳", "子女宮", "己巳", False, ("天機",)),
            ("午", "夫妻宮", "庚午", False, ("紫微",)),
            ("未", "兄弟宮", "辛未", False, ()),
            ("申", "命宮", "壬申", True, ("破軍",)),
            ("酉", "父母宮", "癸酉", False, ()),
            ("戌", "福德宮", "甲戌", False, ("廉貞", "天府")),
            ("亥", "田宅宮", "乙亥", False, ("太陰",)),
        ],
    },
]

# Independent-engine inputs only, not generated expected chart values.
COMPARISON_INPUTS = [
    ("2025-01-29", 0, 30), ("2025-01-29", 1, 30), ("2024-02-29", 12, 0),
    ("2025-01-28", 0, 30), ("2024-02-09", 0, 30), ("2025-07-24", 23, 59),
    ("2025-07-25", 12, 0), ("2025-07-25", 14, 30),
]
