"""Phase 1C source and integration regressions (offline).

Primary rule text, reviewed 2026-10-05:
https://zh.wikisource.org/zh-hant/紫微斗數全書/卷二
Sections 安身命例 and 安十二宮例. First three vectors are explicit examples;
other expected placements below are hand-counted from the same stated rule.
Gregorian/lunar expectations are from the CWA reference in test_calendar.py,
not generated by the placement function or a second calendar-library call.
External calculator availability/conventions are recorded in README.md.
"""

from datetime import date

import pytest
from pydantic import ValidationError

from app.calendar.ganzhi import calculate_calendar
from app.models.birth import BirthData
from app.models.calendar import EARTHLY_BRANCHES, EarthlyBranch, LunarDate
from app.models.ziwei import PalaceLayout
from app.ziwei.palace import calculate_palaces, effective_lunar_month, place_palaces


def lunar(month: int, leap: bool = False, day: int = 1) -> LunarDate:
    """Synthetic rule input, not an assertion that this month exists in 2025."""
    return LunarDate(year=2025, month=month, day=day, is_leap_month=leap)


def birth(solar: str, hour: int, minute: int = 0) -> BirthData:
    civil_date = date.fromisoformat(solar)
    return BirthData(
        gender="female", birthplace="Taipei", birth_year=civil_date.year,
        birth_month=civil_date.month, birth_day=civil_date.day,
        birth_hour=hour, birth_minute=minute,
    )


@pytest.mark.parametrize("hour,life,body", [
    ("子", "寅", "寅"), ("丑", "丑", "卯"), ("寅", "子", "辰"),
])
def test_classical_explicit_examples(hour: EarthlyBranch, life: str, body: str) -> None:
    result = place_palaces(lunar(1), hour)
    assert result.life_palace_branch == life
    assert result.body_palace_branch == body


# Complete source order, independently transcribed; not imported from production.
YIN_LIFE_VECTOR = [
    ("命宮", "寅"), ("兄弟宮", "丑"), ("夫妻宮", "子"), ("子女宮", "亥"),
    ("財帛宮", "戌"), ("疾厄宮", "酉"), ("遷移宮", "申"), ("交友宮", "未"),
    ("官祿宮", "午"), ("田宅宮", "巳"), ("福德宮", "辰"), ("父母宮", "卯"),
]


def test_complete_twelve_palace_vector() -> None:
    result = place_palaces(lunar(1), "子")
    assert [(p.name.value, p.earthly_branch) for p in result.palaces] == YIN_LIFE_VECTOR
    assert [p.name.value for p in result.palaces if p.is_life_palace] == ["命宮"]
    assert [p.name.value for p in result.palaces if p.has_body_palace] == ["命宮"]
    assert result.body_palace_name == "命宮"


@pytest.mark.parametrize("month,hour,life,body,host", [
    (2, "子", "卯", "卯", "命宮"),
    (6, "午", "丑", "丑", "命宮"),
    (7, "未", "丑", "卯", "福德宮"),
    (12, "亥", "寅", "子", "夫妻宮"),
    (11, "丑", "亥", "丑", "福德宮"),
    (1, "卯", "亥", "巳", "遷移宮"),
    (12, "子", "丑", "丑", "命宮"),
    (11, "子", "子", "子", "命宮"),
])
def test_other_months_and_wraparound(
    month: int, hour: EarthlyBranch, life: str, body: str, host: str,
) -> None:
    result = place_palaces(lunar(month), hour)
    assert (result.life_palace_branch, result.body_palace_branch) == (life, body)
    assert result.body_palace_name == host


@pytest.mark.parametrize("hour,expected_host", [
    ("子", "命宮"), ("丑", "福德宮"), ("寅", "官祿宮"), ("卯", "遷移宮"),
    ("辰", "財帛宮"), ("巳", "夫妻宮"), ("午", "命宮"), ("未", "福德宮"),
    ("申", "官祿宮"), ("酉", "遷移宮"), ("戌", "財帛宮"), ("亥", "夫妻宮"),
])
def test_body_host_invariant_for_every_supported_month(
    hour: EarthlyBranch, expected_host: str,
) -> None:
    # All 12 hours x (12 normal + 11 supported leap month inputs) = 276 layouts.
    legal_hosts = {"命宮", "夫妻宮", "財帛宮", "遷移宮", "官祿宮", "福德宮"}
    for leap in (False, True):
        for month in range(1, 12 if leap else 13):
            result = place_palaces(lunar(month, leap), hour)
            assert result.body_palace_name == expected_host
            assert result.body_palace_name in legal_hosts
            assert len(result.palaces) == 12
            assert {p.earthly_branch for p in result.palaces} == set(EARTHLY_BRANCHES)
            assert len({p.name for p in result.palaces}) == 12
            assert sum(p.has_body_palace for p in result.palaces) == 1
            host = next(p for p in result.palaces if p.has_body_palace)
            assert host.earthly_branch == result.body_palace_branch
            assert host.name == result.body_palace_name


@pytest.mark.parametrize("month", range(1, 12))
def test_leap_month_is_always_next_month(month: int) -> None:
    assert effective_lunar_month(lunar(month)) == month
    assert effective_lunar_month(lunar(month, True)) == month + 1


@pytest.mark.parametrize("day", [1, 15, 16, 29])
def test_leap_sixth_month_has_no_midmonth_split(day: int) -> None:
    value = lunar(6, True, day)
    result = place_palaces(value, "未")
    assert result.effective_lunar_month == 7
    assert (result.life_palace_branch, result.body_palace_branch) == ("丑", "卯")
    assert value.month == 6 and value.is_leap_month  # Input is unchanged.


def test_classical_leap_first_month_example() -> None:
    result = place_palaces(lunar(1, True), "子")
    assert result.effective_lunar_month == 2
    assert (result.life_palace_branch, result.body_palace_branch) == ("卯", "卯")


def test_leap_twelfth_month_fails_explicitly() -> None:
    with pytest.raises(ValueError, match="leap month 12"):
        place_palaces(lunar(12, True), "子")


# Independent expected tuples: lunar year/month/day/leap, effective month, Life/Body.
FULL_INPUT_VECTORS = [
    ("2025-01-29", 0, 30, (2025, 1, 1, False), 1, "寅", "寅"),
    ("2025-01-29", 1, 30, (2025, 1, 1, False), 1, "丑", "卯"),
    ("2025-01-29", 3, 30, (2025, 1, 1, False), 1, "子", "辰"),
    ("2024-02-29", 12, 0, (2024, 1, 20, False), 1, "申", "申"),
    ("2025-07-25", 14, 30, (2025, 6, 1, True), 7, "丑", "卯"),
    ("2025-07-25", 12, 0, (2025, 6, 1, True), 7, "寅", "寅"),
    ("2025-07-24", 23, 59, (2025, 6, 30, False), 6, "未", "未"),
    ("2025-07-25", 0, 0, (2025, 6, 1, True), 7, "申", "申"),
]


@pytest.mark.parametrize("solar,hour,minute,expected_lunar,month,life,body", FULL_INPUT_VECTORS)
def test_full_birth_calendar_palace_integration(
    solar: str, hour: int, minute: int, expected_lunar: tuple[int, int, int, bool],
    month: int, life: str, body: str,
) -> None:
    cal = calculate_calendar(birth(solar, hour, minute))
    value = cal.lunar_date
    assert (value.year, value.month, value.day, value.is_leap_month) == expected_lunar
    result = calculate_palaces(cal)
    assert result.effective_lunar_month == month
    assert (result.life_palace_branch, result.body_palace_branch) == (life, body)


def test_leap_month_full_twelve_palace_integration() -> None:
    result = calculate_palaces(calculate_calendar(birth("2025-07-25", 12)))
    assert [(p.name.value, p.earthly_branch) for p in result.palaces] == YIN_LIFE_VECTOR
    assert result.body_palace_name == "命宮"


@pytest.mark.parametrize("hour,minute,branch,life,body", [
    (22, 59, "亥", "申", "午"), (23, 0, "子", "未", "未"),
    (23, 59, "子", "未", "未"), (0, 0, "子", "未", "未"),
])
def test_late_zi_preserves_phase_1b_civil_date(
    hour: int, minute: int, branch: str, life: str, body: str,
) -> None:
    # Use the last day before leap June: advancing at 23:00 would change month.
    cal = calculate_calendar(birth("2025-07-24", hour, minute))
    before = cal.model_dump()
    result = calculate_palaces(cal)
    assert cal.model_dump() == before
    assert cal.solar_date == date(2025, 7, 24)
    assert cal.lunar_date == lunar(6, False, 30)
    assert cal.day_ganzhi.display == "甲午"
    assert result.birth_hour_branch == branch
    assert (result.life_palace_branch, result.body_palace_branch) == (life, body)


def test_uses_lunar_month_not_gregorian_or_month_ganzhi() -> None:
    # Lunar month stays 1 while the solar-term month changes from 丑 to 寅.
    before = calculate_calendar(birth("2025-02-02", 1))
    after = calculate_calendar(birth("2025-02-03", 1))
    assert before.solar_date.month == after.solar_date.month == 2
    assert before.month_ganzhi != after.month_ganzhi
    assert calculate_palaces(before) == calculate_palaces(after)
    assert calculate_palaces(after).life_palace_branch == "丑"


def test_palace_serialization_and_immutable_marker() -> None:
    result = place_palaces(lunar(1), "丑")
    payload = result.model_dump(mode="json")
    assert payload["life_palace_branch"] == "丑"
    assert payload["body_palace_branch"] == "卯"
    assert payload["body_palace_name"] == "福德宮"
    assert len(payload["palaces"]) == 12
    assert sum(p["is_life_palace"] for p in payload["palaces"]) == 1
    assert PalaceLayout.model_validate(result.model_dump(round_trip=True)) == result
    with pytest.raises(ValidationError):
        result.palaces[0].has_body_palace = True


@pytest.mark.parametrize("invalid_branch", ["甲", "子時", "", "壬子"])
def test_invalid_hour_branch_rejected(invalid_branch: str) -> None:
    with pytest.raises(ValueError, match="twelve earthly branches"):
        place_palaces(lunar(1), invalid_branch)


@pytest.mark.parametrize("defect", ["thirteen", "duplicate_branch", "alias", "bad_host", "two_markers"])
def test_inconsistent_layout_rejected(defect: str) -> None:
    payload = place_palaces(lunar(1), "子").model_dump(round_trip=True)
    positions = [dict(p) for p in payload["palaces"]]
    if defect == "thirteen":
        positions.append(dict(positions[0]))
    elif defect == "duplicate_branch":
        positions[1]["earthly_branch"] = positions[0]["earthly_branch"]
    elif defect == "alias":
        positions[7]["name"] = "僕役宮"
    elif defect == "bad_host":
        positions[0]["has_body_palace"] = False
        positions[1]["has_body_palace"] = True
    else:
        positions[2]["has_body_palace"] = True
    payload["palaces"] = positions
    with pytest.raises(ValidationError):
        PalaceLayout.model_validate(payload)
