"""Domain models for Tiger-ZiWei."""

from app.models.birth import BirthData, BirthInput, CalendarType, Gender
from app.models.interpretation import InterpretationResult, OverallInterpretation, PalaceInterpretation
from app.models.flow_year import FlowYearPalace, FlowYearRequest, FlowYearResult, FlowYearTransformation
from app.models.flow_date import (
    FlowDateInput,
    FlowDateRequest,
    FlowDateResult,
    FlowDayPalace,
    FlowDayResult,
    FlowDayTransformation,
    FlowMonthPalace,
    FlowMonthResult,
    FlowMonthTransformation,
)
from app.models.flow_period_interpretation import (
    FlowDayInterpretationFacts,
    FlowDayInterpretationRequest,
    FlowDayInterpretationResult,
    FlowMonthInterpretationFacts,
    FlowMonthInterpretationRequest,
    FlowMonthInterpretationResult,
    FlowPeriodTransformationInterpretation,
)
from app.models.flow_query import (
    FlowQueryInput,
    FlowQueryRequest,
    FlowQueryResult,
    LunarFlowQueryInput,
    NormalizedFlowTarget,
    SolarFlowQueryInput,
)
from app.models.flow_year_interpretation import (
    ActiveMajorLuckInterpretationAnchor,
    ActiveMajorLuckStatus,
    FlowYearInterpretationFacts,
    FlowYearInterpretationRequest,
    FlowYearInterpretationResult,
    FlowYearNatalHostAnchor,
    FlowYearTransformationInterpretation,
)
from app.models.major_luck import (
    MajorLuckDirection,
    MajorLuckPeriod,
    MajorLuckPeriodTransformations,
    MajorLuckResult,
    MajorLuckTransformation,
    YearYinYang,
)
from app.models.major_luck_interpretation import (
    MajorLuckInterpretationFacts,
    MajorLuckInterpretationRequest,
    MajorLuckInterpretationResult,
    MajorLuckTransformationInterpretation,
)
from app.models.report import MajorLuckReportInput, ReportRequest

__all__ = [
    "BirthData",
    "BirthInput",
    "CalendarType",
    "Gender",
    "PalaceInterpretation",
    "OverallInterpretation",
    "InterpretationResult",
    "FlowYearRequest",
    "FlowYearPalace",
    "FlowYearTransformation",
    "FlowYearResult",
    "FlowDateInput",
    "FlowDateRequest",
    "FlowDateResult",
    "FlowMonthPalace",
    "FlowMonthResult",
    "FlowMonthTransformation",
    "FlowDayPalace",
    "FlowDayResult",
    "FlowDayTransformation",
    "FlowMonthInterpretationRequest",
    "FlowMonthInterpretationFacts",
    "FlowMonthInterpretationResult",
    "FlowDayInterpretationRequest",
    "FlowDayInterpretationFacts",
    "FlowDayInterpretationResult",
    "FlowPeriodTransformationInterpretation",
    "SolarFlowQueryInput",
    "LunarFlowQueryInput",
    "FlowQueryInput",
    "FlowQueryRequest",
    "NormalizedFlowTarget",
    "FlowQueryResult",
    "FlowYearInterpretationRequest",
    "FlowYearInterpretationFacts",
    "FlowYearInterpretationResult",
    "FlowYearTransformationInterpretation",
    "FlowYearNatalHostAnchor",
    "ActiveMajorLuckStatus",
    "ActiveMajorLuckInterpretationAnchor",
    "YearYinYang",
    "MajorLuckDirection",
    "MajorLuckPeriod",
    "MajorLuckTransformation",
    "MajorLuckPeriodTransformations",
    "MajorLuckResult",
    "MajorLuckInterpretationRequest",
    "MajorLuckInterpretationFacts",
    "MajorLuckTransformationInterpretation",
    "MajorLuckInterpretationResult",
    "ReportRequest",
    "MajorLuckReportInput",
]
